// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEUurv4gLo_dX6vEYpos_wKjga_unjro8',
    appId: '1:984327333833:web:b54f01a45352795dd0aa18',
    messagingSenderId: '984327333833',
    projectId: 'projects-47efe',
    authDomain: 'projects-47efe.firebaseapp.com',
    storageBucket: 'projects-47efe.firebasestorage.app',
    measurementId: 'G-5V8TFVYXBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXzIH-hDltOYlX85FVGTh5PLvein_EqUg',
    appId: '1:984327333833:android:7060fe39089ea81ad0aa18',
    messagingSenderId: '984327333833',
    projectId: 'projects-47efe',
    storageBucket: 'projects-47efe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5UWs7RBuaQsZPSVDk_sY1Mrjzy1dIdDk',
    appId: '1:984327333833:ios:e9ce896a56a3f42bd0aa18',
    messagingSenderId: '984327333833',
    projectId: 'projects-47efe',
    storageBucket: 'projects-47efe.firebasestorage.app',
    iosBundleId: 'com.example.projectest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5UWs7RBuaQsZPSVDk_sY1Mrjzy1dIdDk',
    appId: '1:984327333833:ios:e9ce896a56a3f42bd0aa18',
    messagingSenderId: '984327333833',
    projectId: 'projects-47efe',
    storageBucket: 'projects-47efe.firebasestorage.app',
    iosBundleId: 'com.example.projectest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEUurv4gLo_dX6vEYpos_wKjga_unjro8',
    appId: '1:984327333833:web:2cbce4c3b82961bcd0aa18',
    messagingSenderId: '984327333833',
    projectId: 'projects-47efe',
    authDomain: 'projects-47efe.firebaseapp.com',
    storageBucket: 'projects-47efe.firebasestorage.app',
    measurementId: 'G-L67CKB6RQC',
  );
}
